version: "0.0.1"
services:
  main:
    image: tourguide-main
    container_name: TG-main
    build:
      context: TourGuideMain
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    networks:
      - web-server
    restart: always
    depends_on:
      - TG-reward
      - TG-gps
      - TG-pricer
  gps:
    image: tourguide-gps
    container_name: TG-gps
    build:
      context: TourGuideGPS
      dockerfile: Dockerfile
    ports: 
      - "8081:8081"
    networks:
      - web-server
    restart: always
  pricer:
    image: tourguide-pricer
    container_name: TG-pricer
    build:
      context: TourGuidePricer
      dockerfile: Dockerfile
    ports: 
      - "8082:8082"
    networks:
      - web-server
    restart: always
  reward:
    image: tourguide-reward
    container_name: TG-reward
    build:
      context: TourGuideReward
      dockerfile: Dockerfile
    ports: 
      - "8083:8083"
    networks:
      - web-server
    restart: always

networks:
  web-server:
    driver: bridge
